name: treat_min
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  custom_switch_button: ^0.5.0
  toggle_switch: ^0.1.8
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: 'fonts/Montserrat-Bold.ttf'
        - asset: 'fonts/Montserrat-Medium.ttf'
        - asset: 'fonts/Montserrat-SemiBold.ttf'

  assets:
    - assets/icons/facebook.png
    - assets/icons/google.png
    - assets/images/doctor.png
    - assets/images/logo.png
    - assets/images/health.png
